#server:
#  port: 8810
#
#spring:
#  application:
#    name: dmall-web-portal
#  boot:
#    admin:
#      client:
#        url: http://localhost:7030 #配置admin-server地址
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#logging:
#  file: admin-client.log #添加开启admin的日志监控
